"use client";

import React, { useState, useEffect } from "react";
import Carousel from "./components/CarouselImage";
import Card from "./components/Card";
import Skeleton, { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";

export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  }, []);
  return (
    <>
      <title>Home | FlickoPedia</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <SkeletonTheme baseColor="#202020" highlightColor="#444">
        {loading ? (
          <Skeleton className=" m-auto h-[200px] md:h-[400px] w-[60%] rounded-xl" />
        ) : (
          <Carousel />
        )}
      </SkeletonTheme>
      <Card />
    </>
  );
}
